// Auto-generated by scripts/buildPlayers.js -- do not edit by hand.
// Regenerate by running: node scripts/buildPlayers.js
//
// Data source: api-football.com (https://www.api-football.com/).
// Each player kept here has 4 or more distinct senior clubs in their career
// (national teams are excluded from that count). Career arrays are ordered
// chronologically; a player who left and later rejoined the same club will
// show up as two separate entries for that club.
//
// Loaded as a plain script (not an ES module) -- include with:
//   <script src="js/careerPlayers.js"></script>

const careerPlayers = {
  easy: [
  {
    name: "Cristiano Ronaldo",
    id: 874,
    photo: "https://media.api-sports.io/football/players/874.png",
    career: [
      { club: "Sporting CP", startYear: 2002, endYear: 2002 },
      { club: "Manchester United", startYear: 2003, endYear: 2008 },
      { club: "Real Madrid", startYear: 2009, endYear: 2017 },
      { club: "Juventus", startYear: 2018, endYear: 2020 },
      { club: "Manchester United", startYear: 2021, endYear: 2021 },
      { club: "Al-Nassr", startYear: 2022, endYear: 2025 },
    ],
  },
  {
    name: "Neymar",
    id: 276,
    photo: "https://media.api-sports.io/football/players/276.png",
    career: [
      { club: "Santos", startYear: 2009, endYear: 2013 },
      { club: "Barcelona", startYear: 2014, endYear: 2016 },
      { club: "Paris Saint Germain", startYear: 2017, endYear: 2022 },
      { club: "Al-Hilal Saudi FC", startYear: 2023, endYear: 2024 },
      { club: "Santos", startYear: 2025, endYear: 2026 },
    ],
  },
  {
    name: "Mohamed Salah",
    id: 306,
    photo: "https://media.api-sports.io/football/players/306.png",
    career: [
      { club: "El Mokawloon", startYear: 2010, endYear: 2011 },
      { club: "FC Basel 1893", startYear: 2012, endYear: 2012 },
      { club: "Chelsea", startYear: 2013, endYear: 2014 },
      { club: "AS Roma", startYear: 2015, endYear: 2016 },
      { club: "Liverpool", startYear: 2017, endYear: 2025 },
    ],
  },
  {
    name: "Kevin De Bruyne",
    id: 629,
    photo: "https://media.api-sports.io/football/players/629.png",
    career: [
      { club: "Genk", startYear: 2008, endYear: 2011 },
      { club: "Chelsea", startYear: 2012, endYear: 2012 },
      { club: "VfL Wolfsburg", startYear: 2013, endYear: 2014 },
      { club: "Manchester City", startYear: 2015, endYear: 2024 },
      { club: "Napoli", startYear: 2025, endYear: 2025 },
    ],
  },
  {
    name: "Robert Lewandowski",
    id: 521,
    photo: "https://media.api-sports.io/football/players/521.png",
    career: [
      { club: "Lech Poznan", startYear: 2008, endYear: 2009 },
      { club: "Borussia Dortmund", startYear: 2010, endYear: 2013 },
      { club: "Bayern München", startYear: 2014, endYear: 2021 },
      { club: "Barcelona", startYear: 2022, endYear: 2025 },
    ],
  },
  {
    name: "Sergio Ramos",
    id: 738,
    photo: "https://media.api-sports.io/football/players/738.png",
    career: [
      { club: "Sevilla", startYear: 2003, endYear: 2005 },
      { club: "Real Madrid", startYear: 2006, endYear: 2020 },
      { club: "Paris Saint Germain", startYear: 2021, endYear: 2022 },
      { club: "Sevilla", startYear: 2023, endYear: 2023 },
      { club: "Monterrey", startYear: 2024, endYear: 2025 },
    ],
  },
  {
    name: "Virgil van Dijk",
    id: 290,
    photo: "https://media.api-sports.io/football/players/290.png",
    career: [
      { club: "Groningen", startYear: 2010, endYear: 2012 },
      { club: "Celtic", startYear: 2013, endYear: 2014 },
      { club: "Southampton", startYear: 2015, endYear: 2016 },
      { club: "Liverpool", startYear: 2017, endYear: 2025 },
    ],
  },
  {
    name: "Sadio Mané",
    id: 304,
    photo: "https://media.api-sports.io/football/players/304.png",
    career: [
      { club: "Metz", startYear: 2011, endYear: 2011 },
      { club: "Red Bull Salzburg", startYear: 2012, endYear: 2013 },
      { club: "Southampton", startYear: 2014, endYear: 2015 },
      { club: "Liverpool", startYear: 2016, endYear: 2021 },
      { club: "Bayern München", startYear: 2022, endYear: 2022 },
      { club: "Al-Nassr", startYear: 2023, endYear: 2025 },
    ],
  },
  {
    name: "Raheem Sterling",
    id: 645,
    photo: "https://media.api-sports.io/football/players/645.png",
    career: [
      { club: "Liverpool", startYear: 2011, endYear: 2014 },
      { club: "Manchester City", startYear: 2015, endYear: 2021 },
      { club: "Chelsea", startYear: 2022, endYear: 2023 },
      { club: "Arsenal", startYear: 2024, endYear: 2024 },
      { club: "Feyenoord", startYear: 2025, endYear: 2025 },
    ],
  },
  {
    name: "Achraf Hakimi",
    id: 9,
    photo: "https://media.api-sports.io/football/players/9.png",
    career: [
      { club: "Real Madrid", startYear: 2016, endYear: 2017 },
      { club: "Borussia Dortmund", startYear: 2018, endYear: 2019 },
      { club: "Inter", startYear: 2020, endYear: 2020 },
      { club: "Paris Saint Germain", startYear: 2021, endYear: 2025 },
    ],
  },
  {
    name: "Álvaro Morata",
    id: 59,
    photo: "https://media.api-sports.io/football/players/59.png",
    career: [
      { club: "Real Madrid", startYear: 2010, endYear: 2013 },
      { club: "Juventus", startYear: 2014, endYear: 2016 },
      { club: "Chelsea", startYear: 2017, endYear: 2017 },
      { club: "Atletico Madrid", startYear: 2018, endYear: 2020 },
      { club: "Juventus", startYear: 2021, endYear: 2021 },
      { club: "Atletico Madrid", startYear: 2022, endYear: 2023 },
      { club: "Galatasaray", startYear: 2024, endYear: 2025 },
    ],
  },
  {
    name: "Memphis Depay",
    id: 667,
    photo: "https://media.api-sports.io/football/players/667.png",
    career: [
      { club: "PSV Eindhoven", startYear: 2011, endYear: 2014 },
      { club: "Manchester United", startYear: 2015, endYear: 2015 },
      { club: "Lyon", startYear: 2016, endYear: 2020 },
      { club: "Barcelona", startYear: 2021, endYear: 2021 },
      { club: "Atletico Madrid", startYear: 2022, endYear: 2023 },
      { club: "Corinthians", startYear: 2024, endYear: 2026 },
    ],
  },
  {
    name: "Pierre-Emerick Aubameyang",
    id: 1465,
    photo: "https://media.api-sports.io/football/players/1465.png",
    career: [
      { club: "AC Milan", startYear: 2007, endYear: 2007 },
      { club: "Dijon", startYear: 2008, endYear: 2008 },
      { club: "Lille", startYear: 2009, endYear: 2009 },
      { club: "Saint Etienne", startYear: 2010, endYear: 2012 },
      { club: "Borussia Dortmund", startYear: 2013, endYear: 2016 },
      { club: "Arsenal", startYear: 2017, endYear: 2020 },
      { club: "Barcelona", startYear: 2021, endYear: 2021 },
      { club: "Chelsea", startYear: 2022, endYear: 2022 },
      { club: "Marseille", startYear: 2023, endYear: 2025 },
    ],
  },
  {
    name: "Wojciech Szczęsny",
    id: 851,
    photo: "https://media.api-sports.io/football/players/851.png",
    career: [
      { club: "Arsenal", startYear: 2008, endYear: 2014 },
      { club: "AS Roma", startYear: 2015, endYear: 2016 },
      { club: "Juventus", startYear: 2017, endYear: 2023 },
      { club: "Barcelona", startYear: 2024, endYear: 2025 },
    ],
  },
  ],
  medium: [
  {
    name: "Victor Osimhen",
    id: 2780,
    photo: "https://media.api-sports.io/football/players/2780.png",
    career: [
      { club: "VfL Wolfsburg", startYear: 2016, endYear: 2017 },
      { club: "Charleroi", startYear: 2018, endYear: 2018 },
      { club: "Lille", startYear: 2019, endYear: 2019 },
      { club: "Napoli", startYear: 2020, endYear: 2023 },
      { club: "Galatasaray", startYear: 2024, endYear: 2025 },
    ],
  },
  {
    name: "Theo Hernández",
    id: 47300,
    photo: "https://media.api-sports.io/football/players/47300.png",
    career: [
      { club: "Atletico Madrid", startYear: 2015, endYear: 2016 },
      { club: "Real Madrid", startYear: 2017, endYear: 2018 },
      { club: "AC Milan", startYear: 2019, endYear: 2024 },
      { club: "Al-Hilal Saudi FC", startYear: 2025, endYear: 2025 },
    ],
  },
  {
    name: "João Cancelo",
    id: 855,
    photo: "https://media.api-sports.io/football/players/855.png",
    career: [
      { club: "Benfica", startYear: 2012, endYear: 2013 },
      { club: "Valencia", startYear: 2014, endYear: 2016 },
      { club: "Inter", startYear: 2017, endYear: 2017 },
      { club: "Juventus", startYear: 2018, endYear: 2018 },
      { club: "Manchester City", startYear: 2019, endYear: 2022 },
      { club: "Barcelona", startYear: 2023, endYear: 2025 },
    ],
  },
  {
    name: "Álvaro Morata",
    id: 59,
    photo: "https://media.api-sports.io/football/players/59.png",
    career: [
      { club: "Real Madrid", startYear: 2010, endYear: 2013 },
      { club: "Juventus", startYear: 2014, endYear: 2016 },
      { club: "Chelsea", startYear: 2017, endYear: 2017 },
      { club: "Atletico Madrid", startYear: 2018, endYear: 2020 },
      { club: "Juventus", startYear: 2021, endYear: 2021 },
      { club: "Atletico Madrid", startYear: 2022, endYear: 2023 },
      { club: "Galatasaray", startYear: 2024, endYear: 2025 },
    ],
  },
  ],
  hard: [

  ],
};
