// data.js
// A list of well-known footballers (current stars + legends of the past).
// This is the only place game "content" lives — main.js just picks from it.

export const players = [
  // Current-era stars
  "Lionel Messi",
  "Cristiano Ronaldo",
  "Kylian Mbappe",
  "Erling Haaland",
  "Neymar",
  "Kevin De Bruyne",
  "Robert Lewandowski",
  "Mohamed Salah",
  "Virgil van Dijk",
  "Karim Benzema",
  "Luka Modric",
  "Sadio Mane",
  "Harry Kane",
  "Son Heung-min",
  "Bruno Fernandes",
  "Vinicius Junior",
  "Jude Bellingham",
  "Rodri",
  "Phil Foden",
  "Bukayo Saka",
  "Declan Rice",
  "Federico Valverde",
  "Antoine Griezmann",
  "Toni Kroos",
  "Casemiro",
  "Thibaut Courtois",
  "Alisson Becker",
  "Ederson",
  "Manuel Neuer",
  "Marc-Andre ter Stegen",
  "Sergio Ramos",
  "Gerard Pique",
  "Raphael Varane",
  "Marquinhos",
  "Ruben Dias",
  "N'Golo Kante",
  "Paul Pogba",
  "Eden Hazard",
  "Gareth Bale",
  "Luis Suarez",
  "Sergio Aguero",
  "David de Gea",
  "Joshua Kimmich",
  "Leon Goretzka",
  "Serge Gnabry",
  "Jamal Musiala",
  "Florian Wirtz",
  "Ilkay Gundogan",
  "Thomas Muller",
  "Manuel Akanji",
  "Achraf Hakimi",
  "Ousmane Dembele",
  "Kingsley Coman",
  "Marco Verratti",
  "Gianluigi Donnarumma",
  "Federico Chiesa",
  "Nicolo Barella",
  "Victor Osimhen",
  "Khvicha Kvaratskhelia",
  "Rafael Leao",
  "Theo Hernandez",
  "Mike Maignan",
  "Dusan Vlahovic",
  "Paulo Dybala",
  "Lautaro Martinez",
  "Julian Alvarez",
  "Enzo Fernandez",
  "Alexis Mac Allister",
  "Rodrigo De Paul",
  "Emiliano Martinez",
  "Nicolas Otamendi",
  "Angel Di Maria",
  "Cody Gakpo",
  "Frenkie de Jong",
  "Memphis Depay",
  "Xavi Simons",
  "Cole Palmer",
  "Trent Alexander-Arnold",
  "Jordan Henderson",
  "Raheem Sterling",
  "Jack Grealish",
  "John Stones",
  "Kyle Walker",
  "Marcus Rashford",
  "Martin Odegaard",
  "William Saliba",
  "Gabriel Jesus",
  "Alexander Isak",
  "Ivan Toney",
  "James Maddison",
  "Moises Caicedo",
  "Wilfried Zaha",
  "Riyad Mahrez",
  "Mohammed Kudus",
  "Andre Onana",
  "Yassine Bounou",
  "Sofyan Amrabat",
  "Hakim Ziyech",

  // Legends of the past
  "Pele",
  "Diego Maradona",
  "Johan Cruyff",
  "Franz Beckenbauer",
  "Zinedine Zidane",
  "Ronaldinho",
  "Ronaldo Nazario",
  "Roberto Carlos",
  "Paolo Maldini",
  "Alessandro Del Piero",
  "Francesco Totti",
  "Andrea Pirlo",
  "Gianluigi Buffon",
  "Fabio Cannavaro",
  "Andres Iniesta",
  "Xavi Hernandez",
  "Carles Puyol",
  "Iker Casillas",
  "Raul Gonzalez",
  "David Villa",
  "Fernando Torres",
  "Xabi Alonso",
  "Sergio Busquets",
  "Thierry Henry",
  "Patrick Vieira",
  "Didier Drogba",
  "Frank Lampard",
  "Steven Gerrard",
  "David Beckham",
  "Wayne Rooney",
  "Paul Scholes",
  "Ryan Giggs",
  "Roy Keane",
  "Eric Cantona",
  "Rio Ferdinand",
  "John Terry",
  "Ashley Cole",
  "Michael Owen",
  "Alan Shearer",
  "Peter Schmeichel",
  "George Best",
  "Bobby Moore",
  "Gordon Banks",
  "Geoff Hurst",
  "Marco van Basten",
  "Ruud Gullit",
  "Frank Rijkaard",
  "Dennis Bergkamp",
  "Clarence Seedorf",
  "Edgar Davids",
  "Patrick Kluivert",
  "Robin van Persie",
  "Arjen Robben",
  "Wesley Sneijder",
  "Michael Ballack",
  "Lothar Matthaus",
  "Jurgen Klinsmann",
  "Oliver Kahn",
  "Karl-Heinz Rummenigge",
  "Gerd Muller",
  "Miroslav Klose",
  "Bastian Schweinsteiger",
  "Philipp Lahm",
  "Mesut Ozil",
  "Marco Reus",
  "Kaka",
  "Rivaldo",
  "Romario",
  "Cafu",
  "Dida",
  "Adriano",
  "Robinho",
  "Hulk",
  "Juan Roman Riquelme",
  "Gabriel Batistuta",
  "Javier Zanetti",
  "Hernan Crespo",
  "Carlos Tevez",
  "Javier Mascherano",
  "Angel Cabrera",
  "Diego Forlan",
  "Luis Figo",
  "Deco",
  "Pepe",
  "Nuno Gomes",
  "Eusebio",
  "George Weah",
  "Samuel Eto'o",
  "Didier Zokora",
  "Michael Essien",
  "Jay-Jay Okocha",
  "Nwankwo Kanu",
  "Yaya Toure",
  "Kolo Toure",
  "Abedi Pele",
  "Roger Milla",
  "Hristo Stoichkov",
  "Zvonimir Boban",
  "Davor Suker",
  "Predrag Mijatovic",
  "Pavel Nedved",
  "Karel Poborsky",
  "Michael Laudrup",
  "Preben Elkjaer",
  "Jari Litmanen",
  "Henrik Larsson",
  "Zlatan Ibrahimovic",
  "Freddie Ljungberg",
  "Alessandro Nesta",
  "Christian Vieri",
  "Filippo Inzaghi",
  "Antonio Cassano",
  "Gianfranco Zola",
  "Roberto Baggio",
  "Salvatore Schillaci",
  "Fabio Grosso",
  "Marcelo",
  "Dani Alves",
  "Diego Milito",
  "Esteban Cambiasso"
];
